project:
  type: book
  output-dir: docs

language: tr.yml

book:
  title: "İstatistik Ders Notları"
  author: "Hüseyin Taştan"
  date: ""
  chapters:
    - index.qmd
    - Giris.qmd
    - R-base.qmd
    - Betimsel.qmd
    - Olasilik.qmd
#    - Kesiklird.qmd
#    - Sureklird.qmd
#    - Normal.qmd
#    - Ornekleme.qmd
#    - Noktatahmini.qmd
#    - Araliktahmini.qmd
#    - Hipotez.qmd
#    - kaynaklar.qmd

#bibliography: kaynaklar.bib
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    papersize: a4paper
    pdf-engine: pdflatex
    fig-format: png
    latex-auto-install: true
    toc: true
    toc-depth: 4
    lot: true
    lof: true
    include-in-header:
      text: |
        \usepackage{makeidx}
        \usepackage{amsmath}
        \usepackage[skip=0.4cm]{caption}
        \makeindex
        \def\K{\mathcal{K}}
        \def\B{\mathcal{B}}
        \def\inv{^{-1}}
        \def\R{\textsc{R}}
        \def\RStudio{\textsc{RStudio }}
        \newcommand{\E}{\mathbb{E}}
        \renewcommand{\P}{\mathbb{P}}
        \newcommand{\V}{\mbox{V}}
        \newcommand{\N}{\mbox{N}}
        \newcommand{\Var}{\mbox{Var}}
        \renewcommand{\vec}{\mbox{vec}}
        \newcommand{\vech}{\mbox{vech}}
        \newcommand{\diag}{\mbox{diag}}
        \newcommand{\Cov}{\mbox{Cov}}
        \newcommand{\trace}{\mbox{trace}}
        \newcommand{\tran}{^\prime}
        \newcommand{\h}{h}
        \newcommand{\plim}{\mbox{plim}}
        \newcommand{\cd}{\overset{d}{\longrightarrow}}
        \newcommand{\cp}{\overset{p}{\longrightarrow}}
        \newcommand{\adistr}{\stackrel{a}{\sim}}
        \newcommand{\ind}{1\hspace{-2.5mm}{1}}
    include-after-body:
      text: |
        \printindex
